2020-04-04 17:11:01,618 ERROR: Exception on /search [GET] [in d:\python\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\main\routes.py", line 148, in search
    current_app.config['POSTS_PER_PAGE'])
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\models.py", line 18, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\search.py", line 24, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "d:\python\lib\site-packages\elasticsearch\client\utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "d:\python\lib\site-packages\elasticsearch\client\__init__.py", line 1627, in search
    body=body,
  File "d:\python\lib\site-packages\elasticsearch\transport.py", line 362, in perform_request
    timeout=timeout,
  File "d:\python\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\python\lib\site-packages\elasticsearch\connection\base.py", line 244, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-04-04 17:15:49,675 ERROR: Exception on /search [GET] [in d:\python\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\main\routes.py", line 148, in search
    current_app.config['POSTS_PER_PAGE'])
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\models.py", line 18, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\search.py", line 24, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "d:\python\lib\site-packages\elasticsearch\client\utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "d:\python\lib\site-packages\elasticsearch\client\__init__.py", line 1627, in search
    body=body,
  File "d:\python\lib\site-packages\elasticsearch\transport.py", line 362, in perform_request
    timeout=timeout,
  File "d:\python\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\python\lib\site-packages\elasticsearch\connection\base.py", line 244, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-04-04 20:35:46,294 ERROR: Exception on /search [GET] [in d:\python\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\main\routes.py", line 148, in search
    current_app.config['POSTS_PER_PAGE'])
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\models.py", line 18, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\search.py", line 24, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "d:\python\lib\site-packages\elasticsearch\client\utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "d:\python\lib\site-packages\elasticsearch\client\__init__.py", line 1627, in search
    body=body,
  File "d:\python\lib\site-packages\elasticsearch\transport.py", line 362, in perform_request
    timeout=timeout,
  File "d:\python\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\python\lib\site-packages\elasticsearch\connection\base.py", line 244, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-04-04 20:39:50,847 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:89]
2020-04-04 20:40:12,570 ERROR: Exception on /search [GET] [in d:\python\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\main\routes.py", line 148, in search
    current_app.config['POSTS_PER_PAGE'])
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\models.py", line 18, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\search.py", line 24, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "d:\python\lib\site-packages\elasticsearch\client\utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "d:\python\lib\site-packages\elasticsearch\client\__init__.py", line 1627, in search
    body=body,
  File "d:\python\lib\site-packages\elasticsearch\transport.py", line 362, in perform_request
    timeout=timeout,
  File "d:\python\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\python\lib\site-packages\elasticsearch\connection\base.py", line 244, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-04-04 20:48:35,727 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:89]
