2020-04-01 16:35:23,021 ERROR: Exception on /user/aa [GET] [in d:\python\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\routes.py", line 100, in user
    return render_template('user.html', user=user, posts=posts)
  File "d:\python\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "d:\python\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\python\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\templates\user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\python\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\python\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "d:\python\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "d:\python\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\templates\user.html", line 24, in block "app_content"
    {% include '_post.html' %}
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\templates\_post.html", line 12, in top-level template code
    said {{ moment(post.timestamp).fromNow() }}:
  File "d:\python\lib\site-packages\flask_moment.py", line 133, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
  File "d:\python\lib\site-packages\flask_moment.py", line 123, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "d:\python\lib\site-packages\flask_moment.py", line 120, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'timestamp'
2020-04-01 16:45:25,179 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:59]
2020-04-01 16:45:57,292 ERROR: Exception on /user/aa [GET] [in d:\python\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\routes.py", line 97, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.confg['POSTS_PER_PAGE'], False)
AttributeError: 'Flask' object has no attribute 'confg'
2020-04-01 16:46:27,225 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:59]
